### PR TITLE
Fix Provisioning

### PR DESCRIPTION
**Pull request by jerryngm**
According to the example provided by ESP: https://github.com/espressif/esp-idf/blob/master/examples/provisioning/wifi_prov_mgr/main/app_main.c Init Provisioning scheme from app_main 
Add WIFI_PROV_CRED_RECV to check and save wifi credential

### CODE REVIEW

**Comment by acvigue** [comment]
Thank you for contributing. I like adding the CRED_RECV event handler, however I don't think it should log the plaintext password. However, I don't understand why you are starting the provisioner in the main function, it is currently started when necessary in the Wi-Fi event handler. The server also will have trouble understanding `thing_name` having a PROV_ prefix.

**Comment by jerryngm** [comment]
Hi Aden, 

Your code make sense totally, however, strangely, once WIFI credentials are saved and ESP is connected to the router it doesn’t automatically get IP from the router so I followed the example from ESP-IDF to init provisioning manager in the main function and it works. 

I added “PROV_” to match the prefix in the ESP Prov app, I don’t think it really matter, we can just keep it as is without the prefix

**Comment by acvigue** [comment]
Can you send a log dump of the issue above being experienced? I have multiple ESP32-S3's running this firmware and none have had issues getting an IP via DHCP.

- Aiden

**Comment by acvigue** [comment]
Closed due to lack of response

**Pull request closed without merging**
